name: Diagnose IONOS Deployment

on:
  push:
    branches:
      - main

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Test SFTP Connection & Log Output
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Testing SFTP connection..."
          sshpass -p "$FTP_PASSWORD" sftp -o StrictHostKeyChecking=no -P "$FTP_PORT" "$FTP_USERNAME@$FTP_HOST" <<EOF
          ls -la
          EOF

      - name: Diagnose Deployment
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Logging diagnostics..."
          {
            echo "==== Server Directory Listing ===="
            sshpass -p "$FTP_PASSWORD" sftp -o StrictHostKeyChecking=no -P "$FTP_PORT" "$FTP_USERNAME@$FTP_HOST" <<< "ls -la"
            echo "==== End of Diagnostics ===="
          } > deploy_log.txt

      - name: Upload Diagnostics Log to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-diagnostics-log
          path: deploy_log.txt
