name: Build and Deploy Automation

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "🚀 Starting Build and Deployment Process"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Avoid shallow clone issues
          submodules: false  # 🚫 Prevent submodule fetching errors
          persist-credentials: false  # Avoid credential conflicts

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Project Files and Build Artifacts
        run: |
          mkdir -p project_files
          echo "Sample content" > project_files/sample.txt
          mkdir -p assets/themes/previews
          echo "Theme preview content" > assets/themes/previews/theme_preview.txt
          mkdir -p build
          echo "Build artifact" > build/app_build.txt

      - name: Pull Latest Changes to Prevent Conflicts
        run: git
