name: Deploy to IONOS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Files to IONOS via SFTP
        uses: appleboy/sftp-action@v0.0.8
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          source: "./"          # Files to upload
          target: "/inaya"     # Remote path on IONOS
          strip_components: 1  # Removes top directory level to avoid nesting
