name: Deploy to GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Copy Project Files (Excluding project_files to prevent recursive copy)
        run: |
          mkdir -p project_files
          rsync -av --exclude='project_files' ./ project_files/

      - name: Commit and Push Changes
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "🚀 Automated commit of project files" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main --force
